# Generated by Django 5.2.11 on 2026-02-19 23:23

from common import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(validators=[validators.validate_description_length]),
        ),
    ]
