# Generated by Django 5.2.11 on 2026-02-19 23:23

import movies.validators
from common import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[validators.validate_description_length]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(validators=[movies.validators.validate_release_year]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(validators=[movies.validators.validate_runtime_positive]),
        ),
    ]
